import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import RelationshipCenter from "./RelationshipCenter";
const contact = { id: "contact-1", name: "Ari", aliases: ["A"], relationshipType: "friend", cadenceDays: 14, privacy: { privateToUser: true, toolReadable: false, delegationSafe: false }, domainIds: ["domain.relationships"], projectIds: [], health: { score: 82, state: "healthy", evidenceConfidence: .64, components: { cadence: { score: 90, source: "last_contact_and_explicit_cadence" }, commitments: { score: 92, source: "commitment_ledger" }, reciprocity: { score: 80, source: "explicit_interaction_evidence" } }, signals: {} }, summary: { interactions: 1, openCommitments: 1, overdueCommitments: 0, pendingFollowups: 1 }, timeline: [{ id: "e1", eventType: "interaction.recorded", actor: "test", payload: { summary: "Call" } }], commitments: [{ id: "c1", title: "Send demo", owner: "self", status: "open", evidence: [] }], followups: [{ id: "f1", intent: "Check in", draft: "Hi", channel: "draft", rationale: "Cadence", status: "pending_approval" }], recommendedAction: { type: "maintain", reason: "ok" } };
const center = { items: [contact], total: 1, summary: { totalContacts: 1, healthy: 1, needsAttention: 0, neglected: 0, openCommitments: 1, pendingFollowups: 1, privateContacts: 1 } };
describe("RelationshipCenter", () => { beforeEach(() => Object.defineProperty(window, "hermesAPI", { configurable: true, value: { getHccRelationships: vi.fn().mockResolvedValue(center), createHccRelationshipContact: vi.fn(), recordHccRelationshipInteraction: vi.fn(), createHccRelationshipCommitment: vi.fn(), transitionHccRelationshipCommitment: vi.fn(), stageHccRelationshipFollowup: vi.fn(), decideHccRelationshipFollowup: vi.fn() } as unknown as typeof window.hermesAPI }));
  it("renders evidence-backed health, privacy, commitments, and timeline", async () => { render(<RelationshipCenter/>); expect(await screen.findByText("Relationship Center")).toBeInTheDocument(); expect(screen.getByText("82 · healthy")).toBeInTheDocument(); expect(screen.getByText("privateToUser true")).toBeInTheDocument(); expect(screen.getByText("reciprocity")).toBeInTheDocument(); expect(screen.getByText("explicit_interaction_evidence")).toBeInTheDocument(); expect(screen.getByText("Send demo · open")).toBeInTheDocument(); expect(screen.getByText("interaction.recorded")).toBeInTheDocument(); });
  it("keeps follow-up human-gated", async () => { render(<RelationshipCenter/>); await screen.findByText("Check in"); fireEvent.click(screen.getByRole("button", { name: "Approve draft refinement" })); await waitFor(() => expect(window.hermesAPI.decideHccRelationshipFollowup).toHaveBeenCalledWith("f1", "approve", "Approved private draft refinement")); });
});
