import { useCallback, useEffect, useState } from "react";

interface Contact { id: string; name: string; aliases: string[]; relationshipType: string; cadenceDays: number; privacy: { privateToUser: boolean; toolReadable: boolean; delegationSafe: boolean }; domainIds: string[]; projectIds: string[]; health: { score: number; state: string; evidenceConfidence: number; components: Record<string, { score: number | null; source: string }>; signals: Record<string, number> }; summary: { interactions: number; openCommitments: number; overdueCommitments: number; pendingFollowups: number }; timeline: Array<{ id: string; eventType: string; actor: string; payload: Record<string, unknown> }>; commitments: Array<{ id: string; title: string; owner: string; status: string; dueAt?: number; evidence: Array<Record<string, unknown>> }>; followups: Array<{ id: string; intent: string; draft: string; channel: string; rationale: string; status: string; executionId?: string }>; recommendedAction: { type: string; reason: string } }
interface Center { items: Contact[]; total: number; summary: { totalContacts: number; healthy: number; needsAttention: number; neglected: number; openCommitments: number; pendingFollowups: number; privateContacts: number } }

function RelationshipCenter(): React.JSX.Element {
  const [center, setCenter] = useState<Center | null>(null); const [selectedId, setSelectedId] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const [contactDraft, setContactDraft] = useState({ name: "", type: "friend", cadence: "14", aliases: "" });
  const [interaction, setInteraction] = useState({ summary: "", evidence: "", reciprocity: "" });
  const [commitment, setCommitment] = useState({ title: "", dueDays: "7" });
  const [followup, setFollowup] = useState({ intent: "", draft: "", channel: "draft", rationale: "" });
  const load = useCallback(async () => { try { const result = await window.hermesAPI.getHccRelationships() as Center; setCenter(result); setSelectedId((current) => current || result.items[0]?.id || null); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Relationship Center unavailable"); } }, []);
  useEffect(() => { void load(); }, [load]); const selected = center?.items.find((item) => item.id === selectedId) || null;
  const run = async (key: string, action: () => Promise<unknown>): Promise<void> => { setBusy(key); setError(null); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Relationship action failed"); } finally { setBusy(null); } };
  const createContact = (): void => { if (!contactDraft.name.trim()) return; void run("contact", async () => { await window.hermesAPI.createHccRelationshipContact({ name: contactDraft.name, relationshipType: contactDraft.type, cadenceDays: Number(contactDraft.cadence), aliases: contactDraft.aliases.split(",").map((x) => x.trim()).filter(Boolean), domainIds: ["domain.relationships"], privacy: { privateToUser: true, toolReadable: false, delegationSafe: false } }); setContactDraft({ ...contactDraft, name: "", aliases: "" }); }); };
  const addInteraction = (): void => { if (!selected || !interaction.summary.trim()) return; void run("interaction", async () => { await window.hermesAPI.recordHccRelationshipInteraction(selected.id, { kind: "note", direction: "mutual", channel: "manual", summary: interaction.summary, reciprocitySignal: interaction.reciprocity ? Number(interaction.reciprocity) : undefined, evidence: interaction.evidence ? [{ type: "operator_evidence", id: interaction.evidence }] : [] }); setInteraction({ summary: "", evidence: "", reciprocity: "" }); }); };
  const addCommitment = (): void => { if (!selected || !commitment.title.trim()) return; void run("commitment", async () => { await window.hermesAPI.createHccRelationshipCommitment(selected.id, { owner: "self", title: commitment.title, dueAt: Date.now() / 1000 + Number(commitment.dueDays) * 86400 }); setCommitment({ ...commitment, title: "" }); }); };
  const stageFollowup = (): void => { if (!selected) return; void run("followup", async () => { await window.hermesAPI.stageHccRelationshipFollowup(selected.id, followup); setFollowup({ intent: "", draft: "", channel: "draft", rationale: "" }); }); };
  return <div className="hcc-project-detail-screen relationship-center-screen">
    <section className="war-room-hero-card"><div><div className="war-room-card-kicker">HCC OS / Private relationship intelligence</div><h1 className="war-room-title">Relationship Center</h1><p className="war-room-subtitle">Honor commitments. Maintain deliberate cadence. Never infer private meaning without evidence.</p></div><button className="war-room-refresh-btn" onClick={() => void load()}>Refresh</button></section>
    {error && <div className="war-room-error-card"><div className="war-room-error-copy">{error}</div></div>}
    <section className="war-room-hero-grid"><article className="war-room-stat-card"><div className="war-room-stat-label">Contacts</div><div className="war-room-stat-value">{center?.summary.totalContacts || 0}</div></article><article className="war-room-stat-card"><div className="war-room-stat-label">Needs attention</div><div className="war-room-stat-value">{center?.summary.needsAttention || 0}</div></article><article className="war-room-stat-card"><div className="war-room-stat-label">Open commitments</div><div className="war-room-stat-value">{center?.summary.openCommitments || 0}</div></article><article className="war-room-stat-card"><div className="war-room-stat-label">Private by default</div><div className="war-room-stat-value">{center?.summary.privateContacts || 0}</div></article></section>
    <section className="war-room-panel relationship-contact-create"><div className="war-room-panel-title">Add canonical contact</div><input aria-label="Contact name" className="war-room-input" placeholder="Name" value={contactDraft.name} onChange={(e) => setContactDraft({ ...contactDraft, name: e.target.value })}/><input aria-label="Contact aliases" className="war-room-input" placeholder="Aliases, comma-separated" value={contactDraft.aliases} onChange={(e) => setContactDraft({ ...contactDraft, aliases: e.target.value })}/><select aria-label="Relationship type" className="war-room-input" value={contactDraft.type} onChange={(e) => setContactDraft({ ...contactDraft, type: e.target.value })}><option>friend</option><option>family</option><option>partner</option><option>mentor</option><option>professional</option></select><input aria-label="Contact cadence" className="war-room-input" type="number" value={contactDraft.cadence} onChange={(e) => setContactDraft({ ...contactDraft, cadence: e.target.value })}/><button className="war-room-refresh-btn relationship-primary" disabled={Boolean(busy)} onClick={createContact}>Add private contact</button></section>
    <section className="relationship-workspace"><aside className="relationship-contact-list">{(center?.items || []).map((contact) => <button key={contact.id} className={`relationship-contact-card ${selectedId === contact.id ? "active" : ""}`} onClick={() => setSelectedId(contact.id)}><strong>{contact.name}</strong><span>{contact.relationshipType} · {contact.health.state}</span><b>{contact.health.score}</b></button>)}</aside>
    {selected && <div className="relationship-detail"><section className="war-room-panel relationship-identity"><div className="decision-head"><div><div className="war-room-item-title">{selected.name}</div><div className="war-room-item-meta">{selected.aliases.join(" · ") || "No aliases"} · cadence {selected.cadenceDays}d</div></div><span className={`war-room-pill tone-${selected.health.state === "healthy" ? "healthy" : "risk"}`}>{selected.health.score} · {selected.health.state}</span></div><div className="decision-profile"><span>privateToUser {String(selected.privacy.privateToUser)}</span><span>toolReadable {String(selected.privacy.toolReadable)}</span><span>delegationSafe {String(selected.privacy.delegationSafe)}</span><span>confidence {selected.health.evidenceConfidence}</span></div><div className="relationship-health-grid">{Object.entries(selected.health.components).map(([key, value]) => <div key={key}><strong>{key}</strong><b>{value.score ?? "unknown"}</b><span>{value.source}</span></div>)}</div></section>
    <section className="relationship-action-grid"><div className="war-room-panel"><div className="war-room-panel-title">Record interaction</div><textarea aria-label="Interaction summary" className="war-room-input" placeholder="What explicitly happened?" value={interaction.summary} onChange={(e) => setInteraction({ ...interaction, summary: e.target.value })}/><input aria-label="Interaction evidence" className="war-room-input" placeholder="Evidence ID" value={interaction.evidence} onChange={(e) => setInteraction({ ...interaction, evidence: e.target.value })}/><input aria-label="Reciprocity evidence score" className="war-room-input" placeholder="Optional 0–1, requires evidence" value={interaction.reciprocity} onChange={(e) => setInteraction({ ...interaction, reciprocity: e.target.value })}/><button className="war-room-refresh-btn" onClick={addInteraction}>Append interaction</button></div><div className="war-room-panel"><div className="war-room-panel-title">Commitment ledger</div><input aria-label="Commitment title" className="war-room-input" placeholder="Promise or commitment" value={commitment.title} onChange={(e) => setCommitment({ ...commitment, title: e.target.value })}/><input aria-label="Commitment due days" className="war-room-input" type="number" value={commitment.dueDays} onChange={(e) => setCommitment({ ...commitment, dueDays: e.target.value })}/><button className="war-room-refresh-btn" onClick={addCommitment}>Record commitment</button>{selected.commitments.map((item) => <div className="relationship-ledger-row" key={item.id}><span>{item.title} · {item.status}</span>{item.status !== "fulfilled" && <button onClick={() => void run(`fulfill:${item.id}`, () => window.hermesAPI.transitionHccRelationshipCommitment(item.id, "fulfilled", [{ type: "operator_confirmation", id: `native-${Date.now()}` }]))}>Fulfill with evidence</button>}</div>)}</div></section>
    <section className="war-room-panel relationship-followup"><div><div className="war-room-card-kicker">Human-gated outreach</div><div className="war-room-panel-title">Stage follow-up draft</div></div><input aria-label="Followup intent" className="war-room-input" placeholder="Intent" value={followup.intent} onChange={(e) => setFollowup({ ...followup, intent: e.target.value })}/><textarea aria-label="Followup draft" className="war-room-input" placeholder="Operator draft" value={followup.draft} onChange={(e) => setFollowup({ ...followup, draft: e.target.value })}/><input aria-label="Followup rationale" className="war-room-input" placeholder="Why now?" value={followup.rationale} onChange={(e) => setFollowup({ ...followup, rationale: e.target.value })}/><button className="war-room-refresh-btn relationship-primary" disabled={!followup.intent || !followup.draft || !followup.rationale} onClick={stageFollowup}>Stage · never auto-send</button>{selected.followups.map((item) => <div className="relationship-followup-row" key={item.id}><div><strong>{item.intent}</strong><span>{item.status} · {item.channel} · {item.executionId || "no execution"}</span></div>{item.status === "pending_approval" && <div className="war-room-action-row"><button onClick={() => void run(`approve:${item.id}`, () => window.hermesAPI.decideHccRelationshipFollowup(item.id, "approve", "Approved private draft refinement"))}>Approve draft refinement</button><button onClick={() => void run(`reject:${item.id}`, () => window.hermesAPI.decideHccRelationshipFollowup(item.id, "reject", "Rejected by operator"))}>Reject</button></div>}</div>)}</section>
    <section className="war-room-panel"><div className="war-room-panel-title">Append-only timeline</div>{selected.timeline.map((event) => <div className="relationship-timeline-row" key={event.id}><strong>{event.eventType}</strong><span>{event.actor}</span><code>{JSON.stringify(event.payload)}</code></div>)}</section></div>}</section>
  </div>;
}
export default RelationshipCenter;
