import type {
  LocalExpertPack,
  LocalExpertRecord,
} from "../../shared/local-experts";

const EXCEL_SCENARIO_SECTIONS = [
  "What to check",
  "Steps",
  "Verification",
  "Risk",
  "Sources",
];

function withExcelRecordDefaults(record: LocalExpertRecord): LocalExpertRecord {
  return {
    freshnessDays: 120,
    commonQuestions: [
      `How do I handle ${record.title.toLowerCase()}?`,
      "What can I verify in Excel or Microsoft 365 without guessing?",
    ],
    dontSay: [
      "Do not claim the current Excel, OneDrive, SharePoint, or Microsoft 365 tenant state unless the user provided evidence.",
      "Do not open Excel files, run VBA macros, run Office Scripts, or change sharing.",
      "Do not ask for Microsoft credentials, call Microsoft Graph, or change tenant/admin policy.",
    ],
    authorityNotes:
      "Prefer Microsoft Support, Microsoft 365, SharePoint, OneDrive, Power Query, and Microsoft Learn documentation. Treat managed work or school tenant policy as authoritative when it restricts sharing, macros, add-ins, or automation.",
    ...record,
  };
}

export const EXCEL_LOCAL_EXPERT_PACK: LocalExpertPack = {
  id: "excel",
  title: "Excel Expert",
  domain: "microsoft-office",
  version: "1.0.1",
  description:
    "Source-backed Microsoft Excel guidance for workbook triage, recovery warnings, formulas, imports, PivotTables, charts, readability cleanup, worksheet organization, workbook protection, sharing, and macro/VBA review.",
  sourceTiers: ["microsoft_365_official", "microsoft_developer_official"],
  recipe: {
    name: "Excel Expert",
    description:
      "Answer Microsoft Excel and Microsoft 365 workbook questions with cited, review-first guidance.",
    job: "Answer Microsoft Excel and Microsoft 365 workbook questions with cited, review-first guidance from the curated Excel Expert records. Ask for visible symptoms, exact warning text, workbook format, storage location, worksheet names, chart context, or screenshots before diagnosing workbook triage issues. Never claim current Excel, OneDrive, SharePoint, or Microsoft 365 tenant state unless evidence is provided. Never claim workbook state unless evidence is provided. Never open Excel files, run VBA macros, run Office Scripts, or change sharing. Never repair workbooks or claim data was recovered. Do not request credentials, call Microsoft Graph, inspect OneDrive or SharePoint directly, change tenant/admin policy, or treat workbook protection as a substitute for safe sharing.",
    inputs:
      "The user's Excel question, visible symptoms, exact warning text if provided, workbook format and storage location if known, account type if known, worksheet or chart context if known, and the installed Excel Expert vault records under expert_excel.",
    output:
      "A concise answer with source-backed checks, steps, verification, risk notes, and source references. If workbook, sharing, macro, worksheet, chart, or tenant evidence is missing, say what the user should inspect in Excel or ask their Microsoft 365 admin to confirm.",
  },
  records: (
    [
      {
        id: "excel-coauthoring-cloud-requirements",
        title: "Coauthor Excel Workbooks From Supported Cloud Locations",
        topic: "excel.coauthoring",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Excel for Microsoft 365",
          "Excel for the web",
          "OneDrive",
          "SharePoint Online",
        ],
        symptoms: [
          "Multiple people cannot edit an Excel workbook at the same time",
          "The workbook opens read-only or does not show other authors' changes",
          "A collaborator can edit in the browser but not in the desktop app",
        ],
        steps: [
          "Confirm the workbook is stored in OneDrive, OneDrive for Business, or a SharePoint Online library.",
          "Confirm the workbook format is .xlsx, .xlsm, or .xlsb, because strict Open XML workbooks do not support coauthoring.",
          "Confirm the user is signed in with a Microsoft 365 subscription account and has a current Excel version that supports coauthoring.",
          "Use Share to invite collaborators and choose whether they can edit or only view.",
          "For managed work or school accounts, collect the exact message if the administrator has not provided a supported version or blocks the workflow.",
        ],
        verification: [
          "The workbook is in a supported OneDrive or SharePoint Online location.",
          "The file format is .xlsx, .xlsm, or .xlsb.",
          "Collaborators can open the workbook and see editing changes or selections according to the platform they use.",
          "Any admin, version, or storage limitation is captured as evidence rather than guessed.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/collaborate-on-excel-workbooks-at-the-same-time-with-co-authoring",
        ],
        lastVerified: "2026-06-22",
        tags: ["coauthoring", "sharing", "onedrive", "sharepoint"],
        commonQuestions: [
          "Why can't two people edit this workbook at the same time?",
          "What does an Excel workbook need before coauthoring works?",
          "Should this workbook be in OneDrive or SharePoint before sharing?",
        ],
        relatedRecordIds: ["excel-sharing-admin-boundaries"],
      },
      {
        id: "excel-sharing-admin-boundaries",
        title: "Recognize SharePoint And OneDrive Sharing Boundaries",
        topic: "microsoft365.sharing.admin",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Microsoft 365",
          "SharePoint Online",
          "OneDrive",
          "Excel workbooks",
        ],
        symptoms: [
          "An external client cannot open a shared Excel workbook",
          "A sharing link works internally but not outside the organization",
          "A work or school account shows administrator-controlled sharing behavior",
        ],
        steps: [
          "Identify whether the workbook is stored in OneDrive or SharePoint.",
          "Collect the link type, external collaborator address, and exact access or policy message.",
          "Check whether organization-level sharing, site-level sharing, OneDrive sharing, link type, or Microsoft Entra B2B settings could be more restrictive than the user expects.",
          "Ask a Microsoft 365 or SharePoint admin to confirm tenant and site policy before suggesting broader external sharing.",
          "Prefer a narrower specific-people link for sensitive workbooks when external sharing is allowed.",
        ],
        verification: [
          "The user can name the storage location, link type, and whether the collaborator is inside or outside the organization.",
          "The exact policy, access request, or sign-in message is captured.",
          "A tenant or site admin confirms any organization-level, site-level, OneDrive, or Microsoft Entra B2B restriction before the workflow changes.",
        ],
        risk: "high",
        sourceUrls: [
          "https://learn.microsoft.com/en-us/sharepoint/turn-external-sharing-on-or-off",
        ],
        lastVerified: "2026-06-22",
        tags: ["sharing", "admin", "onedrive", "sharepoint", "entra"],
        commonQuestions: [
          "External client cannot open this workbook. What should I check first?",
          "Could SharePoint or OneDrive policy block this Excel link?",
          "What should I ask our Microsoft 365 admin to confirm?",
        ],
        relatedRecordIds: [
          "excel-coauthoring-cloud-requirements",
          "excel-protection-passwords",
        ],
      },
      {
        id: "excel-formulas-references",
        title: "Troubleshoot Excel Formulas And References",
        topic: "excel.formulas.references",
        sourceTier: "microsoft_365_official",
        appliesTo: ["Excel for Microsoft 365", "Excel for the web"],
        symptoms: [
          "A formula returns a result that does not match expectations",
          "A copied formula points to the wrong cells",
          "A workbook uses links or external references that may be stale",
        ],
        steps: [
          "Inspect the formula in the Formula bar and confirm it begins with an equal sign.",
          "Separate functions, references, operators, and constants before changing the formula.",
          "Check whether relative, absolute, or mixed cell references changed while copying or filling the formula.",
          "Check whether the formula uses references to another sheet, workbook, or external link.",
          "Compare expected input cells with the actual referenced range before rewriting the formula.",
        ],
        verification: [
          "The exact formula text and referenced cells are visible.",
          "The user can identify functions, references, operators, and constants in the formula.",
          "Relative, absolute, mixed, sheet, workbook, or external references explain the result or are ruled out.",
        ],
        risk: "low",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/overview-of-formulas-in-excel",
        ],
        lastVerified: "2026-06-22",
        tags: ["formulas", "references", "functions", "troubleshooting"],
        commonQuestions: [
          "Why is this Excel formula returning the wrong value?",
          "Should this reference be relative, absolute, or mixed?",
          "What evidence should I collect before rewriting a formula?",
        ],
        relatedRecordIds: ["excel-data-import-power-query"],
      },
      {
        id: "excel-tables-data-validation",
        title: "Use Tables And Data Validation For Controlled Entry",
        topic: "excel.tables.validation",
        sourceTier: "microsoft_365_official",
        appliesTo: ["Excel tables", "Excel data validation"],
        symptoms: [
          "A worksheet needs controlled data entry",
          "Users enter invalid dates, numbers, or status values",
          "A validation command is unavailable because the sheet is protected or shared",
        ],
        steps: [
          "Use tables when the data should have consistent columns and a clear header row.",
          "Use Data Validation to restrict whole numbers, decimals, lists, dates, times, text length, or custom formulas.",
          "For a drop-down list, set the allowed type to List and provide the source values.",
          "Add an input message and error alert so users know what valid data looks like.",
          "If validation controls are unavailable, check whether the worksheet is protected or the workbook is shared before changing the design.",
        ],
        verification: [
          "Invalid input is rejected or warned according to the chosen data validation style.",
          "The drop-down list or custom formula accepts the intended values.",
          "Protected worksheet or shared workbook state is understood before editing validation rules.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/apply-data-validation-to-cells",
        ],
        lastVerified: "2026-06-22",
        tags: ["tables", "data-validation", "dropdowns", "entry"],
        commonQuestions: [
          "How do I stop users from typing invalid values into this sheet?",
          "Why is Data Validation unavailable?",
          "How should I verify a drop-down list works before sharing a workbook?",
        ],
        relatedRecordIds: ["excel-protection-passwords"],
      },
      {
        id: "excel-data-import-power-query",
        title: "Import CSV Data And Use Power Query Carefully",
        topic: "excel.import.power_query",
        sourceTier: "microsoft_365_official",
        appliesTo: ["Excel", "CSV files", "Power Query"],
        symptoms: [
          "Opening a CSV changes dates, identifiers, or leading zeros",
          "A data import needs repeatable cleanup before analysis",
          "A Power Query refresh fails or changes shaped data",
        ],
        steps: [
          "Decide whether to open a .csv directly or import it as an external data range with From Text/CSV.",
          "Inspect delimiters, date formats, numeric identifiers, and leading zeros before accepting inferred data types.",
          "Use Power Query for repeatable extract, transform, and load processing when the same cleanup will happen again.",
          "Review generated Power Query M steps before treating a transformation as reusable.",
          "Remember Excel worksheet limits such as 1,048,576 rows and 16,384 columns when importing large text files.",
        ],
        verification: [
          "The user can show sample source rows, the delimiter, and the imported result.",
          "Identifiers, dates, and leading zeros retain the intended data types.",
          "Power Query steps are reviewable and can be refreshed without silently changing the model.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/import-or-export-text-txt-or-csv-files",
          "https://learn.microsoft.com/en-us/power-query/power-query-what-is-power-query",
        ],
        lastVerified: "2026-06-22",
        tags: ["csv", "import", "power-query", "data-types"],
        commonQuestions: [
          "Why did Excel remove leading zeros from my CSV?",
          "Should I open a CSV directly or import it with From Text/CSV?",
          "When should I use Power Query for repeatable cleanup?",
        ],
        relatedRecordIds: [
          "excel-formulas-references",
          "excel-pivottable-analysis",
        ],
      },
      {
        id: "excel-pivottable-analysis",
        title: "Prepare Source Data Before Building PivotTables",
        topic: "excel.pivottables",
        sourceTier: "microsoft_365_official",
        appliesTo: ["Excel PivotTables", "Excel data model"],
        symptoms: [
          "A PivotTable field list is confusing or missing expected columns",
          "A PivotTable total does not match source data",
          "The user is not sure whether to use a range, table, or data model",
        ],
        steps: [
          "Confirm the source data is organized in columns with a single header row.",
          "Select the cells, table, or range that should feed the PivotTable.",
          "Choose whether the PivotTable belongs in a new worksheet or an existing worksheet.",
          "If Add this data to the Data Model is selected, confirm the workbook model should include that table or range.",
          "Use the field list to arrange fields, then verify filters and source range before trusting totals.",
        ],
        verification: [
          "The selected source range or table has one clear header row and expected fields.",
          "The PivotTable field list contains the intended columns.",
          "Totals, filters, and data model inclusion are checked against source data.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/create-a-pivottable-to-analyze-worksheet-data",
        ],
        lastVerified: "2026-06-22",
        tags: ["pivottables", "analysis", "data-model", "fields"],
        commonQuestions: [
          "Why is my PivotTable missing expected columns?",
          "What source range should I use for this PivotTable?",
          "How do I verify a PivotTable total before sharing it?",
        ],
        relatedRecordIds: [
          "excel-data-import-power-query",
          "excel-formulas-references",
        ],
      },
      {
        id: "excel-charts-office-embedding",
        title: "Create Charts And Understand Office Chart Data",
        topic: "excel.charts.embedding",
        sourceTier: "microsoft_365_official",
        appliesTo: ["Excel charts", "Word charts", "PowerPoint charts"],
        symptoms: [
          "A chart does not reflect the intended data range",
          "A chart in Word or PowerPoint opens Excel data for editing",
          "The user wants a trendline or chart element but is not sure what data is plotted",
        ],
        steps: [
          "Select the data that should appear in the chart before inserting it.",
          "Use Recommended Charts or choose a specific chart type, then preview whether it matches the data.",
          "Review chart title, legend, axis labels, gridlines, and plotted range before sharing.",
          "Add a trendline only when the chart type and data support the intended analysis.",
          "For charts inserted into Word or PowerPoint, remember the chart data is entered and saved in an Excel worksheet inside that document or presentation.",
        ],
        verification: [
          "The chart range contains the intended categories and series.",
          "Chart elements identify what the audience should compare.",
          "Embedded Word or PowerPoint chart data is reviewed through the Excel worksheet that stores it.",
        ],
        risk: "low",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/create-a-chart-from-start-to-finish",
        ],
        lastVerified: "2026-06-22",
        tags: ["charts", "trendlines", "powerpoint", "word", "embedding"],
        commonQuestions: [
          "Why does this chart show the wrong series?",
          "Where is chart data stored in a PowerPoint deck?",
          "What should I verify before sending a chart externally?",
        ],
        relatedRecordIds: [
          "excel-formulas-references",
          "excel-pivottable-analysis",
        ],
      },
      {
        id: "excel-workbook-recovery-repair",
        title: "Triage Workbook Recovery And Repair Warnings",
        topic: "excel.workbook.recovery",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Excel for Microsoft 365",
          "Excel 2024",
          "Excel 2021",
          "Excel 2019",
          "Excel 2016",
        ],
        symptoms: [
          "Excel reports that a workbook is corrupted or starts File Recovery mode",
          "Open and Repair offers to repair a workbook or Extract Data",
          "A disk or network error appears before a workbook can be opened",
        ],
        steps: [
          "Capture the exact warning text, file extension, storage location, and whether the workbook opens at all.",
          "If the file is on a network location or a disk error is involved, move a copy to a local disk before spending time on recovery options.",
          "Use Excel's Open and Repair flow as the source-backed repair path, then choose Repair first when the goal is to recover as much workbook data as possible.",
          "If Repair is not successful, use Extract Data to recover values and formulas where Excel offers that option.",
          "Check whether AutoRecover, a backup copy, a last saved version, or a separate known-good copy exists before attempting risky edits.",
        ],
        verification: [
          "The original workbook is preserved and any recovery attempt uses a copy when possible.",
          "The exact Excel repair, recovery, disk, or network warning is captured as evidence.",
          "Recovered output is compared against a backup copy, AutoRecover file, last saved version, or user-visible expected data before trusting it.",
          "No claim is made that the workbook was repaired unless the user verified the recovered workbook in Excel.",
        ],
        risk: "high",
        sourceUrls: [
          "https://support.microsoft.com/en-us/office/repairing-a-corrupted-workbook-7abfc44d-e9bf-4896-8899-bd10ef4d61ab",
        ],
        lastVerified: "2026-06-24",
        tags: ["recovery", "repair", "corruption", "autorecover", "backup"],
        commonQuestions: [
          "Excel says this workbook is corrupted. What should I check before trying repair?",
          "When should I use Open and Repair versus Extract Data?",
          "How do I preserve evidence before attempting workbook recovery?",
        ],
        relatedRecordIds: [
          "excel-formulas-references",
          "excel-charts-office-embedding",
          "excel-macro-security",
        ],
      },
      {
        id: "excel-embedded-chart-triage",
        title: "Triage Broken Embedded Charts And Chart Data",
        topic: "excel.charts.embedded-triage",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Excel charts",
          "Word charts",
          "PowerPoint charts",
          "Embedded chart data",
        ],
        symptoms: [
          "A chart in Excel, Word, or PowerPoint shows stale or unexpected values",
          "A PowerPoint or Word chart opens an Excel worksheet with sample or wrong data",
          "A linked workbook or corrupted workbook may be affecting chart data",
        ],
        steps: [
          "Identify whether the chart is in Excel, Word, or PowerPoint and whether it is embedded data or a linked workbook.",
          "Inspect the chart range, series names, axis labels, legend, and the Excel worksheet that stores the chart data.",
          "For Word or PowerPoint charts, review the underlying Excel worksheet saved with the document or presentation before changing the visible chart.",
          "If the chart depends on a linked workbook, capture the linked workbook path, warning text, and whether the source workbook opens cleanly.",
          "Do not run a macro to recover chart data from a corrupted workbook in the Local Expert workflow; keep macro guidance to risk review unless the user explicitly provides code for review.",
        ],
        verification: [
          "The chart range and series match the visible worksheet data or the linked workbook evidence.",
          "The user can distinguish embedded Excel worksheet data from a linked workbook dependency.",
          "Word or PowerPoint chart values are checked against the underlying Excel worksheet before sharing.",
          "No macro, Office Script, or workbook repair is treated as completed by the expert.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-us/office/create-a-chart-from-start-to-finish-0baf399e-dd61-4e18-8a73-b3fd5d5680c2",
          "https://support.microsoft.com/en-us/office/repairing-a-corrupted-workbook-7abfc44d-e9bf-4896-8899-bd10ef4d61ab",
        ],
        lastVerified: "2026-06-24",
        tags: ["charts", "embedding", "linked-workbook", "word", "powerpoint"],
        commonQuestions: [
          "Why is this embedded chart showing the wrong data?",
          "How do I tell whether a chart is using embedded data or a linked workbook?",
          "What chart evidence should I collect before rebuilding a chart?",
        ],
        relatedRecordIds: [
          "excel-charts-office-embedding",
          "excel-workbook-recovery-repair",
          "excel-macro-security",
        ],
      },
      {
        id: "excel-gridlines-readability-cleanup",
        title: "Clean Up Gridlines And Worksheet Readability",
        topic: "excel.readability.gridlines",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Excel worksheets",
          "Excel tables",
          "Excel charts",
          "Printed worksheets",
        ],
        symptoms: [
          "A worksheet is hard to read on screen or when printed",
          "Gridlines, borders, or shading make rows and columns unclear",
          "A large sheet loses context when the user scrolls away from headings",
        ],
        steps: [
          "Clarify whether the readability problem is on screen, in print, or inside a chart.",
          "For printed worksheets, check print preview and whether gridlines help rows and columns stand out.",
          "For chart readability, review chart title, axis labels, legend, and chart gridlines before changing chart type.",
          "Use cell formatting, font color, font size, cell styles, or an Excel table when the data needs clearer grouping.",
          "Use Freeze Panes when headers or key columns should stay visible while scrolling through a table or worksheet.",
        ],
        verification: [
          "The worksheet remains readable on screen and in print preview for the user's intended audience.",
          "Gridlines, borders, shading, and table formatting support the data instead of obscuring it.",
          "Frozen rows or columns keep the intended labels visible while scrolling.",
          "No data values, formulas, or sharing permissions are changed as part of readability-only guidance.",
        ],
        risk: "low",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/print-a-worksheet-or-workbook",
          "https://support.microsoft.com/en-US/Excel/get-started/create-a-chart-from-start-to-finish",
          "https://support.microsoft.com/en-US/Excel/get-started/change-the-format-of-a-cell",
          "https://support.microsoft.com/en-US/Excel/get-started/create-and-format-tables",
          "https://support.microsoft.com/en-US/Excel/get-started/freeze-panes-to-lock-rows-and-columns",
        ],
        lastVerified: "2026-06-24",
        tags: [
          "readability",
          "gridlines",
          "print",
          "formatting",
          "freeze-panes",
        ],
        commonQuestions: [
          "How should I clean up gridlines without changing workbook data?",
          "What should I check before formatting a sheet for printing?",
          "Should this sheet use Freeze Panes or table formatting for readability?",
        ],
        relatedRecordIds: [
          "excel-tables-data-validation",
          "excel-charts-office-embedding",
        ],
      },
      {
        id: "excel-worksheet-order-cleanup",
        title: "Clean Up Worksheet Order Safely",
        topic: "excel.worksheet.order",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Excel worksheets",
          "Excel for Microsoft 365",
          "Excel for the web",
        ],
        symptoms: [
          "A workbook has worksheets in a confusing order",
          "Sheets need to be moved, copied, duplicated, or color-coded",
          "Moving a worksheet could affect formulas, charts, or 3-D references",
        ],
        steps: [
          "List the current worksheet names and the intended worksheet order before moving tabs.",
          "Use the Move or Copy Sheet command when organizing sheets in a workbook, including the Before sheet choice or move to end placement.",
          "Use tab colors only as an orientation aid after the worksheet order is clear.",
          "Before moving a sheet to another workbook, check any formulas or charts that refer to data on that sheet.",
          "If 3-D references, Python formulas, Copilot-generated content, charts, pictures, or shapes are involved, verify the result in Excel after moving or copying because web and desktop capabilities differ.",
        ],
        verification: [
          "The final worksheet tab order matches the intended workflow or reporting order.",
          "Formulas or charts that reference moved sheets still point to the intended workbook and worksheet data.",
          "Any 3-D references include or exclude the moved worksheet intentionally.",
          "Excel for the web limitations are not confused with Excel desktop behavior.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-us/office/move-or-copy-worksheets-or-worksheet-data-47207967-bbb2-4e95-9b5c-3c174aa69328",
        ],
        lastVerified: "2026-06-24",
        tags: [
          "worksheets",
          "sheet-tabs",
          "move-copy",
          "3d-references",
          "charts",
        ],
        commonQuestions: [
          "How should I reorder worksheet tabs without breaking formulas?",
          "What should I check before moving a sheet to another workbook?",
          "Why might duplicating a worksheet with charts or shapes fail in Excel for the web?",
        ],
        relatedRecordIds: [
          "excel-formulas-references",
          "excel-charts-office-embedding",
          "excel-workbook-recovery-repair",
        ],
      },
      {
        id: "excel-protection-passwords",
        title: "Understand Excel File Protection And Password Risk",
        topic: "excel.protection.passwords",
        sourceTier: "microsoft_365_official",
        appliesTo: [
          "Excel files",
          "Workbook protection",
          "Worksheet protection",
        ],
        symptoms: [
          "A workbook contains sensitive data",
          "The user wants to prevent others from opening or editing an Excel file",
          "A password-protected workbook needs to be shared safely",
        ],
        steps: [
          "Distinguish file-level protection from workbook or worksheet protection before advising a control.",
          "Use file-level encryption with a password only when the password can be managed safely.",
          "Warn that Microsoft cannot retrieve forgotten passwords.",
          "Warn that distributing password-protected files or passwords can still expose sensitive information if they reach unintended users.",
          "Pair workbook protection decisions with narrow sharing permissions instead of relying on passwords alone.",
        ],
        verification: [
          "The user can name whether the goal is preventing open access, workbook changes, or worksheet edits.",
          "The password handling and sharing path are known before the workbook is distributed.",
          "Sensitive data is not treated as safe only because a password exists.",
        ],
        risk: "high",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started/protect-an-excel-file",
        ],
        lastVerified: "2026-06-22",
        tags: ["protection", "passwords", "sensitive-data", "sharing"],
        commonQuestions: [
          "Should I password-protect this Excel workbook before sending it?",
          "What is the difference between file, workbook, and worksheet protection?",
          "What should I verify before sharing a sensitive workbook?",
        ],
        relatedRecordIds: ["excel-sharing-admin-boundaries"],
      },
      {
        id: "excel-macro-security",
        title: "Review Excel Macro Security Before Trusting A File",
        topic: "excel.macros.security",
        sourceTier: "microsoft_365_official",
        appliesTo: ["Excel macros", "Microsoft 365 Trust Center"],
        symptoms: [
          "Excel shows a macro security warning",
          "A workbook from email or the internet asks to enable content",
          "A managed device blocks macro settings",
        ],
        steps: [
          "Never enable macros unless the user knows what the macros do and wants the functionality.",
          "Treat viewing or editing the workbook as separate from enabling macros.",
          "Review Trust Center macro settings for the current Microsoft 365 app, not all apps.",
          "Prefer disabled macros with notification or digitally signed macros over broad trust.",
          "For managed work or school devices, ask an administrator to confirm policy instead of trying to route around it.",
          "Treat Excel 4.0 XLM macros and VBA project object model access as separate high-risk settings.",
        ],
        verification: [
          "The file origin, security warning, publisher/signature state, and user need for macro functionality are known.",
          "The current app's Trust Center setting is identified without assuming all Office apps match.",
          "No macro is trusted or run without evidence that the user reviewed its purpose and source.",
        ],
        risk: "high",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Office/vba/enable-or-disable-macros-in-microsoft-365-files",
        ],
        lastVerified: "2026-06-22",
        tags: ["macros", "trust-center", "security", "vba", "xlm"],
        commonQuestions: [
          "Excel says macros are disabled. Should I enable content?",
          "Why can I view a workbook without enabling macros?",
          "What macro evidence should I collect before trusting this file?",
        ],
        relatedRecordIds: ["excel-macro-vba-review"],
      },
      {
        id: "excel-macro-vba-review",
        title: "Review Recorded Macros And VBA Object Model Boundaries",
        topic: "excel.macros.vba",
        sourceTier: "microsoft_developer_official",
        appliesTo: ["Excel macros", "VBA", "Visual Basic Editor"],
        symptoms: [
          "A user recorded a macro and wants to understand the generated code",
          "A workbook automation needs to be reviewed before use",
          "A macro interacts with workbook objects in a way the user cannot explain",
        ],
        steps: [
          "Use the Developer tab to record only repeatable workbook actions that the user understands.",
          "Review the generated macro in the Visual Basic Editor before using it on important data.",
          "Use the Excel VBA reference and object model concepts to identify which workbook, worksheet, range, or chart objects the macro touches.",
          "Keep macro guidance to review and explanation unless the user explicitly provides code and asks for a safe edit.",
          "Do not run the macro, change Trust Center settings, or grant VBA project object model access from the expert workflow.",
        ],
        verification: [
          "The user can explain the macro's intended workbook action.",
          "The VBA code and affected Excel object model areas are visible for review.",
          "No macro has been run or trusted as part of the guidance-only expert workflow.",
        ],
        risk: "medium",
        sourceUrls: [
          "https://support.microsoft.com/en-US/Excel/get-started-with-excel/quick-start-create-a-macro",
          "https://learn.microsoft.com/en-us/office/vba/api/overview/excel",
        ],
        lastVerified: "2026-06-22",
        tags: ["macros", "vba", "visual-basic-editor", "object-model"],
        commonQuestions: [
          "What should I review after recording an Excel macro?",
          "How can I tell what workbook objects this VBA touches?",
          "Should this macro be run before someone reviews the code?",
        ],
        relatedRecordIds: ["excel-macro-security"],
      },
    ] satisfies LocalExpertRecord[]
  ).map(withExcelRecordDefaults),
  scenarios: [
    {
      id: "shared-workbook-cannot-coauthor",
      title: "Shared workbook cannot coauthor",
      prompt:
        "A team cannot edit the same Excel workbook at the same time or cannot see each other's workbook changes.",
      recordIds: [
        "excel-coauthoring-cloud-requirements",
        "excel-sharing-admin-boundaries",
      ],
      requiredEvidence: [
        "Workbook storage location: OneDrive, OneDrive for Business, SharePoint Online, or another location",
        "Workbook format: .xlsx, .xlsm, .xlsb, or another format",
        "Whether each collaborator is signed in with a Microsoft 365 subscription account",
        "Exact read-only, version, sync, or administrator message",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "medium",
    },
    {
      id: "external-client-cannot-open-excel",
      title: "External client cannot open Excel workbook",
      prompt:
        "A client outside the organization cannot open or edit a shared Excel workbook.",
      recordIds: [
        "excel-sharing-admin-boundaries",
        "excel-coauthoring-cloud-requirements",
        "excel-protection-passwords",
      ],
      requiredEvidence: [
        "Exact access request, sign-in, or policy message",
        "Current link type and whether it is a specific-people link",
        "Whether the collaborator is outside the Microsoft 365 tenant",
        "Whether file-level password protection or workbook protection is involved",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "high",
    },
    {
      id: "formula-returns-wrong-result",
      title: "Formula returns the wrong result",
      prompt:
        "An Excel formula returns a value the user believes is wrong after copying, filling, or linking workbook data.",
      recordIds: ["excel-formulas-references", "excel-data-import-power-query"],
      requiredEvidence: [
        "Exact formula text from the Formula bar",
        "Expected result and actual result",
        "Referenced cells, sheets, workbooks, or external links",
        "Whether data came from an import or Power Query step",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "medium",
    },
    {
      id: "csv-import-changed-identifiers",
      title: "CSV import changed identifiers",
      prompt:
        "Opening or importing a CSV changed leading zeros, dates, delimiters, or identifier columns.",
      recordIds: [
        "excel-data-import-power-query",
        "excel-tables-data-validation",
        "excel-formulas-references",
      ],
      requiredEvidence: [
        "Sample source rows from the CSV",
        "Delimiter and locale/date format expectations",
        "Columns that should remain text, such as IDs with leading zeros",
        "Whether the file was opened directly or imported with From Text/CSV",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "medium",
    },
    {
      id: "pivottable-source-data-confusing",
      title: "PivotTable source data is confusing",
      prompt:
        "A PivotTable is missing expected fields or produces totals that do not match source data.",
      recordIds: [
        "excel-pivottable-analysis",
        "excel-data-import-power-query",
        "excel-formulas-references",
      ],
      requiredEvidence: [
        "Source range or table name",
        "Header row and expected field names",
        "PivotTable field list, filters, and layout",
        "Whether the data model or Power Query refresh is involved",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "medium",
    },
    {
      id: "macro-security-warning",
      title: "Macro security warning",
      prompt:
        "An Excel workbook shows a macro security warning or asks whether macros should be enabled.",
      recordIds: [
        "excel-macro-security",
        "excel-macro-vba-review",
        "excel-sharing-admin-boundaries",
      ],
      requiredEvidence: [
        "Exact macro security warning text",
        "Where the workbook came from",
        "Whether the macro is signed or from a trusted location",
        "What workbook task the macro is supposed to automate",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "high",
    },
    {
      id: "workbook-repair-warning-triage",
      title: "Workbook repair warning triage",
      prompt:
        "Excel reports that a workbook is corrupted, starts File Recovery mode, or offers Open and Repair or Extract Data.",
      recordIds: [
        "excel-workbook-recovery-repair",
        "excel-formulas-references",
        "excel-macro-security",
      ],
      requiredEvidence: [
        "Exact Excel repair, recovery, disk, or network warning text",
        "Workbook format and whether the original file is preserved",
        "Storage location and whether a local copy can be made",
        "Whether AutoRecover, a backup copy, or a last saved version exists",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "high",
    },
    {
      id: "embedded-chart-broken-data",
      title: "Embedded chart has broken or stale data",
      prompt:
        "A chart in Excel, Word, or PowerPoint shows unexpected values or appears disconnected from the intended workbook data.",
      recordIds: [
        "excel-embedded-chart-triage",
        "excel-charts-office-embedding",
        "excel-workbook-recovery-repair",
      ],
      requiredEvidence: [
        "Whether the chart lives in Excel, Word, or PowerPoint",
        "Chart range, series names, axis labels, and legend context",
        "Whether the chart uses embedded Excel worksheet data or a linked workbook",
        "Any source workbook, link, repair, or update warning text",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "medium",
    },
    {
      id: "gridlines-readability-cleanup",
      title: "Gridlines and readability cleanup",
      prompt:
        "A worksheet is hard to read on screen, in print, or when scrolling through rows and columns.",
      recordIds: [
        "excel-gridlines-readability-cleanup",
        "excel-tables-data-validation",
        "excel-charts-office-embedding",
      ],
      requiredEvidence: [
        "Whether the readability issue is on screen, printed, or inside a chart",
        "Current use of gridlines, borders, shading, table formatting, or cell styles",
        "Rows or columns that should remain visible while scrolling",
        "Whether formulas or data values must remain unchanged",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "low",
    },
    {
      id: "worksheet-order-cleanup",
      title: "Worksheet order cleanup",
      prompt:
        "A workbook's sheet tabs need to be reordered, copied, duplicated, or color-coded without breaking workbook references.",
      recordIds: [
        "excel-worksheet-order-cleanup",
        "excel-formulas-references",
        "excel-charts-office-embedding",
      ],
      requiredEvidence: [
        "Current worksheet names and intended worksheet order",
        "Whether sheets will move within the same workbook or to another workbook",
        "Any formulas, charts, 3-D references, Python formulas, or Copilot-generated content that refer to moved sheets",
        "Whether the user is using Excel desktop or Excel for the web",
      ],
      expectedSections: EXCEL_SCENARIO_SECTIONS,
      risk: "medium",
    },
  ],
};
